#+TITLE: preview-org-html-mode

This minor mode provides an easy preview of your org-exported HTML files using the =xwidget= WebKit browser. Only tested on Emacs 27.1 and 28.0.50 using emacs-plus on OSX. By default when the mode is enabled a save triggers =org-html-export-to-html= and refreshes the xwidget view.

* Usage
** Commands
+ ~preview-org-html-mode~ - begins the preview.
+ ~preview-org-html-refresh~ - refresh preview (only needed in ~'manual~ mode).
+ ~preview-org-html-pop-window-to-frame~ - pops out the current window in to a frame.
** Variables/Configurations
+ ~preview-org-html-refresh-configuration~ - configure how your preview is updated.
  * If ~'save~, update on save (default).
  * If ~'export~, update on manual export (using ~org-html-export-to-html~).
  * If ~'timer~, update preview on timer.
    - Configure with ~preview-org-html-timer-interval~, default 2 seconds
  * If ~'instant~, update ASAP (may cause slowdowns).
    
* Demo
[[preview-org-html-mode-demo]]

* Todos
+ Improve ~'instant~ mode
+ Battle testing
